version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chromamatch_app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
    volumes:
      - .:/app
    depends_on:
      - prometheus
      - grafana
    profiles: ["dev", "test", "prod"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    profiles: ["dev", "test", "prod"]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    profiles: ["dev", "test", "prod"]

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./mlruns:/mlruns
      - ./mlartifacts:/mlartifacts
    profiles: ["dev", "test", "prod"]
